## Load and test the raw dataset

#### **Option 1:** Load the raw data manually

In [2]:
# Load raw 
f_name = "raw_data.csv"

DATA = []

with open(f_name, "r") as fp:
    
    # Get the field names from the first line of the csv
    headers = fp.readline().replace("\n", "").split("\t")
    print("Available fields:", headers) 
    
    # Loop through all lines of the csv file to load the raw data
    for l in fp:
        r = {} # row
        d = l.replace("\n", "").split("\t") # cleanup step
        for k, v in zip(headers, d): # Join headers with data
            r[k] = v
        
        DATA.append(r)
        
print("Total number of rows: {}".format(len(DATA)))

Available fields: ['Timestamp', 'FirstPartyDomain', 'Country', 'RequestedDomain', 'ReferrerDomain', 'RequestType', 'ServerIP']
Total number of rows: 3413570

In [3]:
import pandas as pd

df = pd.DataFrame(DATA)
df

,Timestamp,FirstPartyDomain,Country,RequestedDomain,ReferrerDomain,RequestType,ServerIP
0,1505229096,ant1iwo.com,Cyprus,tpc.googlesyndication.com,bs.serving-sys.com,script,82.199.68.72
1,1505229096,ant1iwo.com,Cyprus,tpc.googlesyndication.com,securepubads.g.doubleclick.net,image,216.58.208.34
2,1505229096,ant1iwo.com,Cyprus,tpc.googlesyndication.com,ds.serving-sys.com,script,195.14.151.154
3,1505229096,ant1iwo.com,Cyprus,tpc.googlesyndication.com,bs.serving-sys.com,script,82.199.68.72
4,1505229096,ant1iwo.com,Cyprus,tpc.googlesyndication.com,ds.serving-sys.com,script,195.14.151.147
...,...,...,...,...,...,...,...
3413565,1577654581,reporter.com.cy,United States,tpc.googlesyndication.com,securepubads.g.doubleclick.net,image,172.217.203.154
3413566,1577654581,reporter.com.cy,United States,ads.tbwa-entelia.com,s0.2mdn.net,script,173.194.216.149
3413567,1577654581,reporter.com.cy,United States,reporter-com-cy.os.tc,cdn.onesignal.com,script,104.18.226.52
3413568,1577654581,reporter.com.cy,United States,reporter-com-cy.os.tc,cdn.onesignal.com,script,104.18.226.52
3413569,1577654581,reporter.com.cy,United States,reporter-com-cy.os.tc,.onesignal.com,script,104.18.225.52

#### **Option 2:** Load the raw data using pandas

In [4]:
# Alternatively, you can load the raw data directly with pandas dataframe
import pandas as pd

f_name = "raw_data.csv"

df = pd.read_csv(f_name, sep="\t")
df

,Timestamp,FirstPartyDomain,Country,RequestedDomain,ReferrerDomain,RequestType,ServerIP
0,1505229096,ant1iwo.com,Cyprus,tpc.googlesyndication.com,bs.serving-sys.com,script,82.199.68.72
1,1505229096,ant1iwo.com,Cyprus,tpc.googlesyndication.com,securepubads.g.doubleclick.net,image,216.58.208.34
2,1505229096,ant1iwo.com,Cyprus,tpc.googlesyndication.com,ds.serving-sys.com,script,195.14.151.154
3,1505229096,ant1iwo.com,Cyprus,tpc.googlesyndication.com,bs.serving-sys.com,script,82.199.68.72
4,1505229096,ant1iwo.com,Cyprus,tpc.googlesyndication.com,ds.serving-sys.com,script,195.14.151.147
...,...,...,...,...,...,...,...
3413565,1577654581,reporter.com.cy,United States,tpc.googlesyndication.com,securepubads.g.doubleclick.net,image,172.217.203.154
3413566,1577654581,reporter.com.cy,United States,ads.tbwa-entelia.com,s0.2mdn.net,script,173.194.216.149
3413567,1577654581,reporter.com.cy,United States,reporter-com-cy.os.tc,cdn.onesignal.com,script,104.18.226.52
3413568,1577654581,reporter.com.cy,United States,reporter-com-cy.os.tc,cdn.onesignal.com,script,104.18.226.52
3413569,1577654581,reporter.com.cy,United States,reporter-com-cy.os.tc,.onesignal.com,script,104.18.225.52

#### Print some raw data statistics, i.e., website visits per user country

In [5]:
df_country = df.groupby(df["Country"]).count()
df_country

,Timestamp,FirstPartyDomain,RequestedDomain,ReferrerDomain,RequestType,ServerIP
Country,,,,,,
Argentina,1683,1683,1683,1683,1683,1683
Austria,2027,2027,2027,2027,2027,2027
Bangladesh,1825,1825,1825,1825,1825,1825
Belgium,2307,2307,2307,2307,2307,2307
Bolivia,4325,4325,4325,4325,4325,4325
Bosnia and Herzegovina,9450,9450,9450,9450,9450,9450
Brazil,76127,76127,76127,76127,76127,76127
Canada,22618,22618,22618,22618,22618,22618
Chile,428,428,428,428,428,428
Colombia,4113,4113,4113,4113,4113,4113
Cyprus,321013,320994,321013,321013,321013,321013
Denmark,64432,64432,64432,64432,64432,64432
Dominican Republic,18835,18835,18835,18835,18835,18835
Egypt,157372,157372,157372,157372,157372,157372
Estonia,32,32,32,32,32,32
Finland,617,617,617,617,617,617
France,1343,1343,1343,1343,1343,1343
Germany,116637,116614,116637,116637,116637,116637
Greece,49808,49808,49808,49808,49808,49808
Hungary,44,44,44,44,44,44
Iceland,30,30,30,30,30,30
India,36653,36653,36653,36653,36653,36653
Indonesia,1864,1864,1864,1864,1864,1864
Italy,15132,15132,15132,15132,15132,15132
Japan,207,207,207,207,207,207
Kenya,6173,6173,6173,6173,6173,6173
Macedonia,47377,47377,47377,47377,47377,47377
Malaysia,147,147,147,147,147,147
Mexico,1469,1469,1469,1469,1469,1469
Nepal,1162,1162,1162,1162,1162,1162
Netherlands,25,25,25,25,25,25
Pakistan,65,65,65,65,65,65
Peru,15622,15622,15622,15622,15622,15622
Poland,264,264,264,264,264,264
Portugal,72,72,72,72,72,72
Republic of Moldova,10600,10600,10600,10600,10600,10600
Romania,167832,167832,167832,167832,167832,167832
Russia,62721,62721,62721,62721,62721,62721
Saudi Arabia,26852,26852,26852,26852,26852,26852
Serbia,12193,12193,12193,12193,12193,12193
Singapore,409,409,409,409,409,409
South Africa,147,147,147,147,147,147
Spain,834212,834212,834212,834212,834212,834212
Sri Lanka,726,726,726,726,726,726
Switzerland,371,371,371,371,371,371
Tunisia,7517,7517,7517,7517,7517,7517
Turkey,63573,63529,63573,63573,63573,63573
Ukraine,27769,27769,27769,27769,27769,27769
United Arab Emirates,224,224,224,224,224,224
United Kingdom,232499,232499,232499,232499,232499,232499
United States,13297,13297,13297,13297,13297,13297
Venezuela,962115,962111,962115,962115,962115,962115
Vietnam,3087,3087,3087,3087,3087,3087

In [6]:
df_types = df.groupby(df["RequestType"]).count()
df_types

,Timestamp,FirstPartyDomain,Country,RequestedDomain,ReferrerDomain,ServerIP
RequestType,,,,,,
csp_report,5,5,5,5,5,5
font,173763,173749,172929,173763,173763,173763
image,1645136,1645092,1642393,1645136,1645136,1645136
media,2009,2009,2009,2009,2009,2009
object,10,10,10,10,10,10
other,1343,1343,1343,1343,1343,1343
ping,35745,35745,35725,35745,35745,35745
script,946142,946119,944770,946142,946142,946142
stylesheet,142163,142160,141789,142163,142163,142163
sub_frame,305682,305679,305215,305682,305682,305682
xmlhttprequest,161572,161569,161254,161572,161572,161572